-- =====================================================================
--  POPUP 스키마 — Oracle DDL (PostgreSQL popup 스키마 변환)
-- =====================================================================
--  원본   : WPF_WindowsPopupWithC_sample / ERD/01_schema.sql (popup 스키마 16 테이블)
--  기준   : 기준0.1.txt 항목 5 (PostgreSQL → Oracle 변환)
--  대상   : Oracle 19c (가정. README "설계 전제" 참조)
--  실행자 : POPUP 스키마 소유 계정 (또는 DBA가 CURRENT_SCHEMA 지정)
--  원칙   : 테이블·컬럼 구성은 원본과 동일하게 유지하고 Oracle 문법으로만 변환한다.
--           신설은 §11 결과 수신 영수증 1개 테이블만이다.
--           (인증 토큰 테이블은 두지 않는다. 토큰 인증은 타 팀이 웹·WPF 통합 토큰으로 개발 — docs/04)
--
--  변환 규칙 요약 (상세: docs/05_Oracle_DB_설계.md)
--    VARCHAR(n)                      → VARCHAR2(n CHAR)   (문자 단위 길이 유지)
--    TEXT                            → CLOB
--    JSONB                           → CLOB + CHECK (... IS JSON)
--    BIGINT IDENTITY                 → NUMBER(19) + 시퀀스 SEQ_<TABLE> (MyBatis selectKey BEFORE)
--    INTEGER / NUMERIC(p,s)          → NUMBER(10) / NUMBER(p,s)
--    TIMESTAMP                       → TIMESTAMP(6)  (KST 로컬 시각 저장, 변환은 Java에서)
--    DATE                            → DATE          (시각 00:00:00으로 저장)
--    CURRENT_TIMESTAMP               → CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP)  (DB 서버 시간대와 무관하게 KST 저장. 매퍼의 nowKst와 동일)
--    부분 유니크 인덱스 (WHERE ...)  → 함수 기반 유니크 인덱스 (CASE WHEN ... THEN key END)
--    num_nonnulls(a,b,c,d) = 1       → (CASE WHEN a IS NOT NULL THEN 1 ELSE 0 END + ...) = 1
--    CHECK (CASE ... ELSE FALSE END) → CHECK (CASE ... THEN 1 ELSE 0 END = 1)
--    ON DELETE CASCADE               → 동일
--    COMMENT ON                      → 동일
--    SET LOCAL search_path           → ALTER SESSION SET CURRENT_SCHEMA
--
--  주의
--    * 이 스크립트는 신규 스키마용이다. 기존 테이블이 있으면 실행하지 않는다.
--    * 12.1 이하 Oracle은 식별자 30바이트 제한이 있어 일부 제약명이 길다. 19c 전제.
--    * 조직 마스터(APP_DEPARTMENT/APP_POSITION/APP_USER)는 운영 HR 마스터 연동 방식이
--      확정되면 뷰 또는 동기화 테이블로 대체될 수 있다. 구조는 원본 유지.
-- =====================================================================

ALTER SESSION SET CURRENT_SCHEMA = POPUP;

-- ---------------------------------------------------------------------
-- §0. 시퀀스 (원본 IDENTITY 컬럼 1개당 1개)
-- ---------------------------------------------------------------------
CREATE SEQUENCE SEQ_QUESTION_TEMPLATE       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_POPUP_TARGET_GROUP      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_POPUP_TARGET_CONDITION  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_POPUP_QUESTION          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_POPUP_OPTION            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USER_POPUP_STATUS       START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_POPUP_RESPONSE          START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_POPUP_RESPONSE_ANSWER   START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_POPUP_RESPONSE_VALUE    START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_VIDEO_VIEW_STATUS       START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_API_REQUEST_LOG         START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE;
CREATE SEQUENCE SEQ_WPF_RESULT_RECEIPT      START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE;

-- ---------------------------------------------------------------------
-- §1. 조직 마스터
-- ---------------------------------------------------------------------
CREATE TABLE APP_DEPARTMENT
(
    DEPARTMENT_ID        VARCHAR2(30 CHAR)  NOT NULL,
    PARENT_DEPARTMENT_ID VARCHAR2(30 CHAR),
    DEPARTMENT_NAME      VARCHAR2(100 CHAR) NOT NULL,
    DEPARTMENT_LEVEL     NUMBER(10)         NOT NULL,
    SORT_ORDER           NUMBER(10)         NOT NULL,
    ACTIVE_YN            CHAR(1)            DEFAULT 'Y' NOT NULL,
    CREATED_BY           VARCHAR2(30 CHAR)  NOT NULL,
    CREATED_AT           TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    UPDATED_BY           VARCHAR2(30 CHAR)  NOT NULL,
    UPDATED_AT           TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_APP_DEPARTMENT PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT FK_DEPARTMENT_PARENT FOREIGN KEY (PARENT_DEPARTMENT_ID)
        REFERENCES APP_DEPARTMENT (DEPARTMENT_ID),
    CONSTRAINT CK_DEPARTMENT_LEVEL      CHECK (DEPARTMENT_LEVEL >= 1),
    CONSTRAINT CK_DEPARTMENT_SORT_ORDER CHECK (SORT_ORDER >= 0),
    CONSTRAINT CK_DEPARTMENT_ACTIVE     CHECK (ACTIVE_YN IN ('Y', 'N'))
);
COMMENT ON TABLE  APP_DEPARTMENT IS '부서 마스터. 팝업 대상 조건(DEPARTMENT)과 하위 부서 포함 판단에 사용';
COMMENT ON COLUMN APP_DEPARTMENT.PARENT_DEPARTMENT_ID IS '상위 부서. 하위 포함 조건은 재귀 조회로 판단';

CREATE TABLE APP_POSITION
(
    POSITION_ID   VARCHAR2(30 CHAR)  NOT NULL,
    POSITION_NAME VARCHAR2(100 CHAR) NOT NULL,
    SORT_ORDER    NUMBER(10)         NOT NULL,
    ACTIVE_YN     CHAR(1)            DEFAULT 'Y' NOT NULL,
    CREATED_BY    VARCHAR2(30 CHAR)  NOT NULL,
    CREATED_AT    TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    UPDATED_BY    VARCHAR2(30 CHAR)  NOT NULL,
    UPDATED_AT    TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_APP_POSITION PRIMARY KEY (POSITION_ID),
    CONSTRAINT CK_POSITION_SORT_ORDER CHECK (SORT_ORDER >= 0),
    CONSTRAINT CK_POSITION_ACTIVE     CHECK (ACTIVE_YN IN ('Y', 'N'))
);
COMMENT ON TABLE APP_POSITION IS '직급 마스터. 팝업 대상 조건(POSITION)에 사용';

CREATE TABLE APP_USER
(
    EMPLOYEE_NO   VARCHAR2(30 CHAR)  NOT NULL,
    EMPLOYEE_NAME VARCHAR2(100 CHAR) NOT NULL,
    DEPARTMENT_ID VARCHAR2(30 CHAR)  NOT NULL,
    POSITION_ID   VARCHAR2(30 CHAR)  NOT NULL,
    ACTIVE_YN     CHAR(1)            DEFAULT 'Y' NOT NULL,
    HIRE_DATE     DATE,
    LAST_LOGIN_AT TIMESTAMP(6),
    CREATED_BY    VARCHAR2(30 CHAR)  NOT NULL,
    CREATED_AT    TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    UPDATED_BY    VARCHAR2(30 CHAR)  NOT NULL,
    UPDATED_AT    TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_APP_USER PRIMARY KEY (EMPLOYEE_NO),
    CONSTRAINT FK_USER_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES APP_DEPARTMENT (DEPARTMENT_ID),
    CONSTRAINT FK_USER_POSITION   FOREIGN KEY (POSITION_ID)   REFERENCES APP_POSITION (POSITION_ID),
    CONSTRAINT CK_USER_ACTIVE CHECK (ACTIVE_YN IN ('Y', 'N'))
);
COMMENT ON TABLE  APP_USER IS '사용자(사번) 마스터. WPF 토큰의 사번과 대상 계산의 기준 키';
COMMENT ON COLUMN APP_USER.EMPLOYEE_NO IS '사번. SSO가 반환하는 사용자 식별자와 일치해야 함';
COMMENT ON COLUMN APP_USER.HIRE_DATE   IS '입사일. 대상 조건 HIRE_DATE 비교 대상 (시각 없음)';

-- ---------------------------------------------------------------------
-- §2. 문항 템플릿
-- ---------------------------------------------------------------------
CREATE TABLE QUESTION_TEMPLATE
(
    QUESTION_TEMPLATE_ID NUMBER(19)         NOT NULL,
    TEMPLATE_GROUP_ID    VARCHAR2(30 CHAR)  NOT NULL,
    TEMPLATE_NAME        VARCHAR2(100 CHAR) NOT NULL,
    TEMPLATE_TYPE        VARCHAR2(10 CHAR)  NOT NULL,
    TEMPLATE_VERSION     NUMBER(10)         NOT NULL,
    CURRENT_YN           CHAR(1)            DEFAULT 'Y' NOT NULL,
    ACTIVE_YN            CHAR(1)            DEFAULT 'Y' NOT NULL,
    CREATED_BY           VARCHAR2(30 CHAR)  NOT NULL,
    CREATED_AT           TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    UPDATED_BY           VARCHAR2(30 CHAR)  NOT NULL,
    UPDATED_AT           TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_QUESTION_TEMPLATE PRIMARY KEY (QUESTION_TEMPLATE_ID),
    CONSTRAINT UK_QUESTION_TEMPLATE_GROUP_VERSION UNIQUE (TEMPLATE_GROUP_ID, TEMPLATE_VERSION),
    CONSTRAINT CK_QUESTION_TEMPLATE_VERSION CHECK (TEMPLATE_VERSION >= 1),
    CONSTRAINT CK_QUESTION_TEMPLATE_CURRENT CHECK (CURRENT_YN IN ('Y', 'N')),
    CONSTRAINT CK_QUESTION_TEMPLATE_ACTIVE  CHECK (ACTIVE_YN IN ('Y', 'N'))
);
COMMENT ON TABLE  QUESTION_TEMPLATE IS '재사용·버전 관리되는 문항 템플릿 (원본: Reusable and versioned question template)';
COMMENT ON COLUMN QUESTION_TEMPLATE.TEMPLATE_GROUP_ID IS '템플릿 그룹. 원본 gen_random_uuid() → Oracle SUBSTR(RAWTOHEX(SYS_GUID()),1,30)';

-- 원본: CREATE UNIQUE INDEX ux_question_template_current ON question_template (template_group_id) WHERE current_yn = 'Y';
-- Oracle은 부분 인덱스가 없으므로 함수 기반 유니크 인덱스로 변환한다.
-- CURRENT_YN <> 'Y' 인 행은 NULL 키가 되어 유니크 검사 대상에서 제외된다.
CREATE UNIQUE INDEX UX_QUESTION_TEMPLATE_CURRENT
    ON QUESTION_TEMPLATE (CASE WHEN CURRENT_YN = 'Y' THEN TEMPLATE_GROUP_ID END);

-- ---------------------------------------------------------------------
-- §3. 팝업 정의
-- ---------------------------------------------------------------------
CREATE TABLE POPUP_NOTICE
(
    POPUP_ID                       VARCHAR2(50 CHAR)  NOT NULL,
    QUESTION_TEMPLATE_ID           NUMBER(19),
    POPUP_TYPE                     VARCHAR2(20 CHAR)  NOT NULL,
    TITLE                          VARCHAR2(200 CHAR) NOT NULL,
    SHOW_ON_LOGIN_YN               CHAR(1)            DEFAULT 'N' NOT NULL,
    SHOW_ON_SCHEDULE_YN            CHAR(1)            DEFAULT 'N' NOT NULL,
    SCHEDULED_AT                   TIMESTAMP(6),
    DISPLAY_START_AT               TIMESTAMP(6)       NOT NULL,
    DISPLAY_END_AT                 TIMESTAMP(6)       NOT NULL,
    DISPLAY_MODE                   VARCHAR2(20 CHAR)  NOT NULL,
    DISPLAY_ORDER                  NUMBER(10)         DEFAULT 100 NOT NULL,
    PERIOD_MODE                    VARCHAR2(20 CHAR)  NOT NULL,
    REPEAT_INTERVAL                NUMBER(10),
    REPEAT_DAY_OF_WEEK             VARCHAR2(20 CHAR),
    REPEAT_DAY_OF_MONTH            NUMBER(10),
    ACTIVE_YN                      CHAR(1)            DEFAULT 'Y' NOT NULL,
    SIZE_MODE                      VARCHAR2(30 CHAR)  NOT NULL,
    POPUP_WIDTH                    NUMBER(10,2),
    POPUP_HEIGHT                   NUMBER(10,2),
    WIDTH_RATIO                    NUMBER(5,4),
    HEIGHT_RATIO                   NUMBER(5,4),
    MINIMUM_WIDTH                  NUMBER(10,2),
    MINIMUM_HEIGHT                 NUMBER(10,2),
    MAXIMUM_WIDTH                  NUMBER(10,2),
    MAXIMUM_HEIGHT                 NUMBER(10,2),
    SHOW_HEADER_YN                 CHAR(1)            DEFAULT 'Y' NOT NULL,
    SHOW_CLOSE_BUTTON_YN           CHAR(1)            DEFAULT 'Y' NOT NULL,
    SHOW_FOOTER_YN                 CHAR(1)            DEFAULT 'Y' NOT NULL,
    SHOW_DO_NOT_SHOW_AGAIN_YN      CHAR(1)            DEFAULT 'N' NOT NULL,
    HIDE_DAYS                      NUMBER(10),
    COMPLETION_RATIO               NUMBER(5,4),
    PASSING_SCORE                  NUMBER(10,2),
    ALLOW_CLOSE_BEFORE_COMPLETE_YN CHAR(1)            DEFAULT 'Y' NOT NULL,
    CREATED_BY                     VARCHAR2(30 CHAR)  NOT NULL,
    CREATED_AT                     TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    UPDATED_BY                     VARCHAR2(30 CHAR)  NOT NULL,
    UPDATED_AT                     TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_POPUP_NOTICE PRIMARY KEY (POPUP_ID),
    CONSTRAINT FK_POPUP_QUESTION_TEMPLATE FOREIGN KEY (QUESTION_TEMPLATE_ID)
        REFERENCES QUESTION_TEMPLATE (QUESTION_TEMPLATE_ID),
    CONSTRAINT CK_POPUP_DISPLAY_ORDER  CHECK (DISPLAY_ORDER >= 1),
    CONSTRAINT CK_POPUP_DISPLAY_PERIOD CHECK (DISPLAY_END_AT >= DISPLAY_START_AT),
    CONSTRAINT CK_POPUP_SCHEDULED_AT   CHECK (SHOW_ON_SCHEDULE_YN = 'N' OR SCHEDULED_AT IS NOT NULL),
    CONSTRAINT CK_POPUP_REPEAT_INTERVAL CHECK (REPEAT_INTERVAL IS NULL OR REPEAT_INTERVAL >= 1),
    CONSTRAINT CK_POPUP_REPEAT_DAY_OF_MONTH CHECK (REPEAT_DAY_OF_MONTH IS NULL OR REPEAT_DAY_OF_MONTH BETWEEN 1 AND 31),
    CONSTRAINT CK_POPUP_HIDE_DAYS        CHECK (HIDE_DAYS IS NULL OR HIDE_DAYS >= 1),
    CONSTRAINT CK_POPUP_COMPLETION_RATIO CHECK (COMPLETION_RATIO IS NULL OR COMPLETION_RATIO BETWEEN 0 AND 1),
    CONSTRAINT CK_POPUP_PASSING_SCORE    CHECK (PASSING_SCORE IS NULL OR PASSING_SCORE >= 0),
    CONSTRAINT CK_POPUP_WIDTH_RATIO      CHECK (WIDTH_RATIO IS NULL OR WIDTH_RATIO > 0),
    CONSTRAINT CK_POPUP_HEIGHT_RATIO     CHECK (HEIGHT_RATIO IS NULL OR HEIGHT_RATIO > 0),
    CONSTRAINT CK_POPUP_YN_VALUES CHECK
        (SHOW_ON_LOGIN_YN IN ('Y', 'N')
         AND SHOW_ON_SCHEDULE_YN IN ('Y', 'N')
         AND ACTIVE_YN IN ('Y', 'N')
         AND SHOW_HEADER_YN IN ('Y', 'N')
         AND SHOW_CLOSE_BUTTON_YN IN ('Y', 'N')
         AND SHOW_FOOTER_YN IN ('Y', 'N')
         AND SHOW_DO_NOT_SHOW_AGAIN_YN IN ('Y', 'N')
         AND ALLOW_CLOSE_BEFORE_COMPLETE_YN IN ('Y', 'N'))
);
COMMENT ON TABLE  POPUP_NOTICE IS '팝업 공통 설정. WPF 목록 응답의 평면 필드 원본';
COMMENT ON COLUMN POPUP_NOTICE.POPUP_TYPE IS 'TEXT / IMAGE / VIDEO / SURVEY / QUIZ';
COMMENT ON COLUMN POPUP_NOTICE.DISPLAY_MODE IS 'SEQUENTIAL / SIMULTANEOUS';
COMMENT ON COLUMN POPUP_NOTICE.SIZE_MODE IS 'FIXED / RATIO / FULLSCREEN';
COMMENT ON COLUMN POPUP_NOTICE.COMPLETION_RATIO IS 'VIDEO 완료 기준 시청 비율 0~1. NULL이면 1.0';
COMMENT ON COLUMN POPUP_NOTICE.PASSING_SCORE IS 'QUIZ 통과 점수. WPF 응답에는 내려주지 않음';
COMMENT ON COLUMN POPUP_NOTICE.PERIOD_MODE IS '기간/반복 모드. 반복 정책은 미확정으로 값만 보존';

CREATE TABLE POPUP_CONTENT
(
    POPUP_ID        VARCHAR2(50 CHAR)   NOT NULL,
    CONTENT_TITLE   VARCHAR2(200 CHAR),
    DESCRIPTION     VARCHAR2(2000 CHAR),
    CONTENT_BODY    CLOB,
    MEDIA_URL       VARCHAR2(2000 CHAR),
    LINK_URL        VARCHAR2(2000 CHAR),
    CONTENT_OPTIONS CLOB,
    CREATED_BY      VARCHAR2(30 CHAR)   NOT NULL,
    CREATED_AT      TIMESTAMP(6)        DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    UPDATED_BY      VARCHAR2(30 CHAR)   NOT NULL,
    UPDATED_AT      TIMESTAMP(6)        DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_POPUP_CONTENT PRIMARY KEY (POPUP_ID),
    CONSTRAINT FK_CONTENT_POPUP FOREIGN KEY (POPUP_ID)
        REFERENCES POPUP_NOTICE (POPUP_ID) ON DELETE CASCADE,
    -- 원본 JSONB. Oracle 19c는 CLOB + IS JSON 체크로 JSON 유효성을 보장한다.
    CONSTRAINT CK_CONTENT_OPTIONS_JSON CHECK (CONTENT_OPTIONS IS JSON)
);
COMMENT ON TABLE  POPUP_CONTENT IS '유형별 콘텐츠. 제목·설명·본문·미디어URL은 정규 컬럼, 나머지 옵션은 CONTENT_OPTIONS JSON';
COMMENT ON COLUMN POPUP_CONTENT.CONTENT_BODY IS 'TEXT 유형 plainText 본문 (원본 TEXT → CLOB)';
COMMENT ON COLUMN POPUP_CONTENT.CONTENT_OPTIONS IS '확장 옵션 JSON (원본 JSONB → CLOB IS JSON). content 조립은 Java에서 수행';

CREATE TABLE POPUP_TARGET_GROUP
(
    TARGET_GROUP_ID    NUMBER(19)         NOT NULL,
    POPUP_ID           VARCHAR2(50 CHAR)  NOT NULL,
    TARGET_NAME        VARCHAR2(100 CHAR) NOT NULL,
    TARGET_DESCRIPTION VARCHAR2(500 CHAR) NOT NULL,
    GROUP_ORDER        NUMBER(10)         NOT NULL,
    CREATED_BY         VARCHAR2(30 CHAR)  NOT NULL,
    CREATED_AT         TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    UPDATED_BY         VARCHAR2(30 CHAR)  NOT NULL,
    UPDATED_AT         TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_POPUP_TARGET_GROUP PRIMARY KEY (TARGET_GROUP_ID),
    CONSTRAINT FK_TARGET_GROUP_POPUP FOREIGN KEY (POPUP_ID)
        REFERENCES POPUP_NOTICE (POPUP_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_TARGET_GROUP_ORDER UNIQUE (POPUP_ID, GROUP_ORDER),
    CONSTRAINT CK_TARGET_GROUP_ORDER CHECK (GROUP_ORDER >= 1)
);
COMMENT ON TABLE POPUP_TARGET_GROUP IS '노출 대상 그룹. 그룹 간 OR';

CREATE TABLE POPUP_TARGET_CONDITION
(
    TARGET_CONDITION_ID  NUMBER(19)        NOT NULL,
    TARGET_GROUP_ID      NUMBER(19)        NOT NULL,
    CONDITION_TYPE       VARCHAR2(30 CHAR) NOT NULL,
    CONDITION_OPERATOR   VARCHAR2(10 CHAR) NOT NULL,
    DEPARTMENT_ID        VARCHAR2(30 CHAR),
    POSITION_ID          VARCHAR2(30 CHAR),
    EMPLOYEE_NO          VARCHAR2(30 CHAR),
    CONDITION_DATE_VALUE DATE,
    INCLUDE_CHILD_YN     CHAR(1)           DEFAULT 'N' NOT NULL,
    CONDITION_ORDER      NUMBER(10)        NOT NULL,
    CREATED_BY           VARCHAR2(30 CHAR) NOT NULL,
    CREATED_AT           TIMESTAMP(6)      DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    UPDATED_BY           VARCHAR2(30 CHAR) NOT NULL,
    UPDATED_AT           TIMESTAMP(6)      DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_POPUP_TARGET_CONDITION PRIMARY KEY (TARGET_CONDITION_ID),
    CONSTRAINT FK_TARGET_CONDITION_GROUP FOREIGN KEY (TARGET_GROUP_ID)
        REFERENCES POPUP_TARGET_GROUP (TARGET_GROUP_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TARGET_CONDITION_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES APP_DEPARTMENT (DEPARTMENT_ID),
    CONSTRAINT FK_TARGET_CONDITION_POSITION   FOREIGN KEY (POSITION_ID)   REFERENCES APP_POSITION (POSITION_ID),
    CONSTRAINT FK_TARGET_CONDITION_EMPLOYEE   FOREIGN KEY (EMPLOYEE_NO)   REFERENCES APP_USER (EMPLOYEE_NO),
    CONSTRAINT UQ_TARGET_CONDITION_ORDER UNIQUE (TARGET_GROUP_ID, CONDITION_ORDER),
    CONSTRAINT CK_TARGET_CONDITION_ORDER CHECK (CONDITION_ORDER >= 1),
    CONSTRAINT CK_TARGET_CONDITION_INCLUDE_CHILD CHECK (INCLUDE_CHILD_YN IN ('Y', 'N')),
    CONSTRAINT CK_TARGET_CONDITION_OPERATOR CHECK (CONDITION_OPERATOR IN ('=', '!=', '<', '<=', '>', '>=')),
    -- 원본: num_nonnulls(department_id, position_id, employee_no, condition_date_value) = 1
    --       AND CASE condition_type WHEN 'DEPARTMENT' THEN department_id IS NOT NULL ... ELSE FALSE END
    -- Oracle CHECK는 boolean 결과의 CASE를 허용하지 않아 1/0 정수로 변환한다.
    CONSTRAINT CK_TARGET_CONDITION_VALUE CHECK
    (
        (CASE WHEN DEPARTMENT_ID        IS NOT NULL THEN 1 ELSE 0 END
       + CASE WHEN POSITION_ID          IS NOT NULL THEN 1 ELSE 0 END
       + CASE WHEN EMPLOYEE_NO          IS NOT NULL THEN 1 ELSE 0 END
       + CASE WHEN CONDITION_DATE_VALUE IS NOT NULL THEN 1 ELSE 0 END) = 1
        AND
        (CASE CONDITION_TYPE
            WHEN 'DEPARTMENT' THEN CASE WHEN DEPARTMENT_ID        IS NOT NULL THEN 1 ELSE 0 END
            WHEN 'POSITION'   THEN CASE WHEN POSITION_ID          IS NOT NULL THEN 1 ELSE 0 END
            WHEN 'EMPLOYEE'   THEN CASE WHEN EMPLOYEE_NO          IS NOT NULL THEN 1 ELSE 0 END
            WHEN 'HIRE_DATE'  THEN CASE WHEN CONDITION_DATE_VALUE IS NOT NULL THEN 1 ELSE 0 END
            ELSE 0
         END) = 1
    ),
    CONSTRAINT CK_TARGET_CONDITION_CHILD_DEPARTMENT CHECK (INCLUDE_CHILD_YN = 'N' OR CONDITION_TYPE = 'DEPARTMENT')
);
COMMENT ON TABLE  POPUP_TARGET_CONDITION IS '노출 대상 조건. 같은 그룹 내 AND. 유형별 값 컬럼 중 정확히 1개만 사용';
COMMENT ON COLUMN POPUP_TARGET_CONDITION.CONDITION_TYPE IS 'DEPARTMENT / POSITION / EMPLOYEE / HIRE_DATE';
COMMENT ON COLUMN POPUP_TARGET_CONDITION.CONDITION_DATE_VALUE IS 'CONDITION_TYPE이 HIRE_DATE일 때 비교 날짜';

-- ---------------------------------------------------------------------
-- §4. 문항·선택지
-- ---------------------------------------------------------------------
CREATE TABLE POPUP_QUESTION
(
    QUESTION_ID          NUMBER(19)          NOT NULL,
    QUESTION_TEMPLATE_ID NUMBER(19)          NOT NULL,
    QUESTION_TYPE        VARCHAR2(30 CHAR)   NOT NULL,
    QUESTION_TITLE       VARCHAR2(1000 CHAR) NOT NULL,
    QUESTION_DESCRIPTION VARCHAR2(2000 CHAR),
    REQUIRED_YN          CHAR(1)             DEFAULT 'N' NOT NULL,
    SCORED_YN            CHAR(1)             DEFAULT 'N' NOT NULL,
    QUESTION_SCORE       NUMBER(10,2),
    CORRECT_ANSWER       CLOB,
    ANSWER_MATCH_MODE    VARCHAR2(10 CHAR),
    SORT_ORDER           NUMBER(10)          NOT NULL,
    CREATED_BY           VARCHAR2(30 CHAR)   NOT NULL,
    CREATED_AT           TIMESTAMP(6)        DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    UPDATED_BY           VARCHAR2(30 CHAR)   NOT NULL,
    UPDATED_AT           TIMESTAMP(6)        DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_POPUP_QUESTION PRIMARY KEY (QUESTION_ID),
    CONSTRAINT FK_QUESTION_TEMPLATE FOREIGN KEY (QUESTION_TEMPLATE_ID)
        REFERENCES QUESTION_TEMPLATE (QUESTION_TEMPLATE_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_QUESTION_SORT_ORDER UNIQUE (QUESTION_TEMPLATE_ID, SORT_ORDER),
    CONSTRAINT CK_QUESTION_SORT_ORDER CHECK (SORT_ORDER >= 1),
    CONSTRAINT CK_QUESTION_MATCH_MODE CHECK (ANSWER_MATCH_MODE IS NULL OR ANSWER_MATCH_MODE IN ('EXACT', 'CONTAINS')),
    CONSTRAINT CK_QUESTION_YN_VALUES CHECK (REQUIRED_YN IN ('Y', 'N') AND SCORED_YN IN ('Y', 'N')),
    CONSTRAINT CK_QUESTION_SCORE CHECK
        ((SCORED_YN = 'Y' AND QUESTION_SCORE IS NOT NULL AND QUESTION_SCORE >= 0)
         OR (SCORED_YN = 'N' AND QUESTION_SCORE IS NULL))
);
COMMENT ON TABLE  POPUP_QUESTION IS '문항. QUESTION_TYPE: SINGLE_CHOICE / MULTIPLE_CHOICE / TEXT (기존 데이터 RATING5 허용)';
COMMENT ON COLUMN POPUP_QUESTION.CORRECT_ANSWER IS '서술형 정답(관리자 전용, WPF 응답 제외). 원본 TEXT → CLOB';

CREATE TABLE POPUP_OPTION
(
    OPTION_ID    NUMBER(19)          NOT NULL,
    QUESTION_ID  NUMBER(19)          NOT NULL,
    OPTION_VALUE VARCHAR2(200 CHAR)  NOT NULL,
    OPTION_TEXT  VARCHAR2(1000 CHAR) NOT NULL,
    CORRECT_YN   CHAR(1)             DEFAULT 'N' NOT NULL,
    SORT_ORDER   NUMBER(10)          NOT NULL,
    CREATED_BY   VARCHAR2(30 CHAR)   NOT NULL,
    CREATED_AT   TIMESTAMP(6)        DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    UPDATED_BY   VARCHAR2(30 CHAR)   NOT NULL,
    UPDATED_AT   TIMESTAMP(6)        DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_POPUP_OPTION PRIMARY KEY (OPTION_ID),
    CONSTRAINT FK_OPTION_QUESTION FOREIGN KEY (QUESTION_ID)
        REFERENCES POPUP_QUESTION (QUESTION_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_OPTION_VALUE      UNIQUE (QUESTION_ID, OPTION_VALUE),
    CONSTRAINT UQ_OPTION_SORT_ORDER UNIQUE (QUESTION_ID, SORT_ORDER),
    CONSTRAINT CK_OPTION_SORT_ORDER CHECK (SORT_ORDER >= 1),
    CONSTRAINT CK_OPTION_CORRECT    CHECK (CORRECT_YN IN ('Y', 'N'))
);
COMMENT ON TABLE  POPUP_OPTION IS '선택지. CORRECT_YN은 관리자 전용, WPF 응답 제외';

-- ---------------------------------------------------------------------
-- §5. 사용자별 팝업 상태 (표시·닫기·숨김·완료)
-- ---------------------------------------------------------------------
CREATE TABLE USER_POPUP_STATUS
(
    USER_POPUP_STATUS_ID NUMBER(19)        NOT NULL,
    EMPLOYEE_NO          VARCHAR2(30 CHAR) NOT NULL,
    POPUP_ID             VARCHAR2(50 CHAR) NOT NULL,
    POPUP_STATUS         VARCHAR2(30 CHAR) NOT NULL,
    FIRST_DISPLAYED_AT   TIMESTAMP(6),
    LAST_DISPLAYED_AT    TIMESTAMP(6),
    DISPLAY_COUNT        NUMBER(10)        DEFAULT 0 NOT NULL,
    CLOSED_AT            TIMESTAMP(6),
    HIDDEN_FROM_AT       TIMESTAMP(6),
    HIDDEN_UNTIL_AT      TIMESTAMP(6),
    COMPLETED_YN         CHAR(1)           DEFAULT 'N' NOT NULL,
    COMPLETED_AT         TIMESTAMP(6),
    CREATED_BY           VARCHAR2(30 CHAR) NOT NULL,
    CREATED_AT           TIMESTAMP(6)      DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    UPDATED_BY           VARCHAR2(30 CHAR) NOT NULL,
    UPDATED_AT           TIMESTAMP(6)      DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_USER_POPUP_STATUS PRIMARY KEY (USER_POPUP_STATUS_ID),
    CONSTRAINT UQ_USER_POPUP_STATUS UNIQUE (EMPLOYEE_NO, POPUP_ID),
    CONSTRAINT FK_STATUS_USER  FOREIGN KEY (EMPLOYEE_NO) REFERENCES APP_USER (EMPLOYEE_NO),
    CONSTRAINT FK_STATUS_POPUP FOREIGN KEY (POPUP_ID) REFERENCES POPUP_NOTICE (POPUP_ID) ON DELETE CASCADE,
    CONSTRAINT CK_STATUS_DISPLAY_COUNT CHECK (DISPLAY_COUNT >= 0),
    CONSTRAINT CK_STATUS_COMPLETED     CHECK (COMPLETED_YN IN ('Y', 'N')),
    CONSTRAINT CK_STATUS_HIDDEN_PERIOD CHECK
        (HIDDEN_UNTIL_AT IS NULL OR HIDDEN_FROM_AT IS NULL OR HIDDEN_UNTIL_AT >= HIDDEN_FROM_AT)
);
COMMENT ON TABLE  USER_POPUP_STATUS IS '사용자×팝업 1행. WPF 결과 API가 종료 시점에 1회 갱신. 노출 계산의 숨김·완료 판단 원본';
COMMENT ON COLUMN USER_POPUP_STATUS.POPUP_STATUS IS 'DISPLAYED / CLOSED / HIDDEN / SUBMITTED / COMPLETED';
COMMENT ON COLUMN USER_POPUP_STATUS.COMPLETED_YN IS 'Y이면 조회에서 제외 (SURVEY/QUIZ 통과/VIDEO 완료)';

-- ---------------------------------------------------------------------
-- §6. 설문·퀴즈 응답
-- ---------------------------------------------------------------------
CREATE TABLE POPUP_RESPONSE
(
    RESPONSE_ID          NUMBER(19)         NOT NULL,
    CLIENT_REQUEST_ID    VARCHAR2(100 CHAR) NOT NULL,
    POPUP_ID             VARCHAR2(50 CHAR)  NOT NULL,
    EMPLOYEE_NO          VARCHAR2(30 CHAR)  NOT NULL,
    QUESTION_TEMPLATE_ID NUMBER(19),
    RESPONSE_STATUS      VARCHAR2(30 CHAR)  NOT NULL,
    RESPONSE_STARTED_AT  TIMESTAMP(6),
    SUBMITTED_AT         TIMESTAMP(6),
    RECEIVED_AT          TIMESTAMP(6),
    TOTAL_SCORE          NUMBER(10,2),
    PASSED_YN            CHAR(1),
    CREATED_BY           VARCHAR2(30 CHAR)  NOT NULL,
    CREATED_AT           TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    UPDATED_BY           VARCHAR2(30 CHAR)  NOT NULL,
    UPDATED_AT           TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_POPUP_RESPONSE PRIMARY KEY (RESPONSE_ID),
    CONSTRAINT UQ_RESPONSE_REQUEST    UNIQUE (CLIENT_REQUEST_ID),
    CONSTRAINT UQ_RESPONSE_USER_POPUP UNIQUE (EMPLOYEE_NO, POPUP_ID),
    CONSTRAINT FK_RESPONSE_POPUP FOREIGN KEY (POPUP_ID) REFERENCES POPUP_NOTICE (POPUP_ID),
    CONSTRAINT FK_RESPONSE_USER  FOREIGN KEY (EMPLOYEE_NO) REFERENCES APP_USER (EMPLOYEE_NO),
    CONSTRAINT FK_RESPONSE_QUESTION_TEMPLATE FOREIGN KEY (QUESTION_TEMPLATE_ID)
        REFERENCES QUESTION_TEMPLATE (QUESTION_TEMPLATE_ID),
    CONSTRAINT CK_RESPONSE_PASSED      CHECK (PASSED_YN IS NULL OR PASSED_YN IN ('Y', 'N')),
    CONSTRAINT CK_RESPONSE_TOTAL_SCORE CHECK (TOTAL_SCORE IS NULL OR TOTAL_SCORE >= 0)
);
COMMENT ON TABLE  POPUP_RESPONSE IS '사용자×팝업 최신 응답 1건(원본 정책 유지). 재제출 시 MERGE 후 하위 답안 교체';
COMMENT ON COLUMN POPUP_RESPONSE.CLIENT_REQUEST_ID IS 'WPF 결과 항목의 resultId를 저장';
COMMENT ON COLUMN POPUP_RESPONSE.TOTAL_SCORE IS 'QUIZ만 사용. SURVEY는 NULL';

CREATE TABLE POPUP_RESPONSE_ANSWER
(
    RESPONSE_ANSWER_ID NUMBER(19)        NOT NULL,
    RESPONSE_ID        NUMBER(19)        NOT NULL,
    QUESTION_ID        NUMBER(19)        NOT NULL,
    TEXT_ANSWER        CLOB,
    EARNED_SCORE       NUMBER(10,2),
    CORRECT_YN         CHAR(1),
    CREATED_BY         VARCHAR2(30 CHAR) NOT NULL,
    CREATED_AT         TIMESTAMP(6)      DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    UPDATED_BY         VARCHAR2(30 CHAR) NOT NULL,
    UPDATED_AT         TIMESTAMP(6)      DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_POPUP_RESPONSE_ANSWER PRIMARY KEY (RESPONSE_ANSWER_ID),
    CONSTRAINT UQ_RESPONSE_QUESTION UNIQUE (RESPONSE_ID, QUESTION_ID),
    CONSTRAINT FK_ANSWER_RESPONSE FOREIGN KEY (RESPONSE_ID)
        REFERENCES POPUP_RESPONSE (RESPONSE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ANSWER_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES POPUP_QUESTION (QUESTION_ID),
    CONSTRAINT CK_ANSWER_EARNED_SCORE CHECK (EARNED_SCORE IS NULL OR EARNED_SCORE >= 0),
    CONSTRAINT CK_ANSWER_CORRECT      CHECK (CORRECT_YN IS NULL OR CORRECT_YN IN ('Y', 'N'))
);
COMMENT ON TABLE POPUP_RESPONSE_ANSWER IS '문항별 답안. 서술형은 TEXT_ANSWER, 선택형은 POPUP_RESPONSE_VALUE';

CREATE TABLE POPUP_RESPONSE_VALUE
(
    RESPONSE_VALUE_ID  NUMBER(19)         NOT NULL,
    RESPONSE_ANSWER_ID NUMBER(19)         NOT NULL,
    OPTION_ID          NUMBER(19),
    SELECTED_VALUE     VARCHAR2(200 CHAR) NOT NULL,
    CREATED_BY         VARCHAR2(30 CHAR)  NOT NULL,
    CREATED_AT         TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    UPDATED_BY         VARCHAR2(30 CHAR)  NOT NULL,
    UPDATED_AT         TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_POPUP_RESPONSE_VALUE PRIMARY KEY (RESPONSE_VALUE_ID),
    CONSTRAINT FK_VALUE_ANSWER FOREIGN KEY (RESPONSE_ANSWER_ID)
        REFERENCES POPUP_RESPONSE_ANSWER (RESPONSE_ANSWER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_VALUE_OPTION FOREIGN KEY (OPTION_ID) REFERENCES POPUP_OPTION (OPTION_ID)
);
COMMENT ON TABLE POPUP_RESPONSE_VALUE IS '선택형 답안의 선택지. 선택지 삭제 대비 SELECTED_VALUE를 함께 보관';

-- ---------------------------------------------------------------------
-- §7. 영상 시청 상태 (결과 API 종료 시 1회 갱신)
-- ---------------------------------------------------------------------
CREATE TABLE VIDEO_VIEW_STATUS
(
    VIDEO_VIEW_STATUS_ID     NUMBER(19)        NOT NULL,
    EMPLOYEE_NO              VARCHAR2(30 CHAR) NOT NULL,
    POPUP_ID                 VARCHAR2(50 CHAR) NOT NULL,
    TOTAL_DURATION_SECONDS   NUMBER(12,3),
    LAST_POSITION_SECONDS    NUMBER(12,3),
    MAXIMUM_POSITION_SECONDS NUMBER(12,3),
    WATCHED_SECONDS          NUMBER(12,3),
    WATCHED_RATIO            NUMBER(5,4),
    COMPLETED_YN             CHAR(1)           DEFAULT 'N' NOT NULL,
    FIRST_PLAYED_AT          TIMESTAMP(6),
    LAST_PLAYED_AT           TIMESTAMP(6),
    COMPLETED_AT             TIMESTAMP(6),
    CREATED_BY               VARCHAR2(30 CHAR) NOT NULL,
    CREATED_AT               TIMESTAMP(6)      DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    UPDATED_BY               VARCHAR2(30 CHAR) NOT NULL,
    UPDATED_AT               TIMESTAMP(6)      DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_VIDEO_VIEW_STATUS PRIMARY KEY (VIDEO_VIEW_STATUS_ID),
    CONSTRAINT UQ_VIDEO_VIEW_STATUS UNIQUE (EMPLOYEE_NO, POPUP_ID),
    CONSTRAINT FK_VIDEO_STATUS_USER  FOREIGN KEY (EMPLOYEE_NO) REFERENCES APP_USER (EMPLOYEE_NO),
    CONSTRAINT FK_VIDEO_STATUS_POPUP FOREIGN KEY (POPUP_ID) REFERENCES POPUP_NOTICE (POPUP_ID) ON DELETE CASCADE,
    CONSTRAINT CK_VIDEO_COMPLETED        CHECK (COMPLETED_YN IN ('Y', 'N')),
    CONSTRAINT CK_VIDEO_DURATION         CHECK (TOTAL_DURATION_SECONDS IS NULL OR TOTAL_DURATION_SECONDS >= 0),
    CONSTRAINT CK_VIDEO_LAST_POSITION    CHECK (LAST_POSITION_SECONDS IS NULL OR LAST_POSITION_SECONDS >= 0),
    CONSTRAINT CK_VIDEO_MAXIMUM_POSITION CHECK (MAXIMUM_POSITION_SECONDS IS NULL OR MAXIMUM_POSITION_SECONDS >= 0),
    CONSTRAINT CK_VIDEO_WATCHED_SECONDS  CHECK (WATCHED_SECONDS IS NULL OR WATCHED_SECONDS >= 0),
    CONSTRAINT CK_VIDEO_WATCHED_RATIO    CHECK (WATCHED_RATIO IS NULL OR WATCHED_RATIO BETWEEN 0 AND 1)
);
COMMENT ON TABLE VIDEO_VIEW_STATUS IS '영상 시청 누적. 실시간 진행률 전송을 제거했으므로 팝업 종료 시 1회 MERGE(최대값 유지)';

-- ---------------------------------------------------------------------
-- §8. API 요청 로그 (WPF 결과 API 처리 로그로 사용)
-- ---------------------------------------------------------------------
CREATE TABLE API_REQUEST_LOG
(
    API_REQUEST_LOG_ID    NUMBER(19)          NOT NULL,
    CLIENT_REQUEST_ID     VARCHAR2(100 CHAR),
    EMPLOYEE_NO           VARCHAR2(30 CHAR),
    POPUP_ID              VARCHAR2(50 CHAR),
    API_PATH              VARCHAR2(1000 CHAR) NOT NULL,
    HTTP_METHOD           VARCHAR2(10 CHAR)   NOT NULL,
    CLIENT_IP             VARCHAR2(100 CHAR),
    REQUEST_RECEIVED_AT   TIMESTAMP(6)        NOT NULL,
    RESPONSE_COMPLETED_AT TIMESTAMP(6),
    ELAPSED_MILLISECONDS  NUMBER(19),
    HTTP_STATUS_CODE      NUMBER(10),
    SUCCESS_YN            CHAR(1)             NOT NULL,
    ERROR_CODE            VARCHAR2(100 CHAR),
    ERROR_MESSAGE         CLOB,
    REQUEST_SUMMARY       CLOB,
    RESPONSE_SUMMARY      CLOB,
    CREATED_BY            VARCHAR2(30 CHAR)   NOT NULL,
    CREATED_AT            TIMESTAMP(6)        DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    UPDATED_BY            VARCHAR2(30 CHAR)   NOT NULL,
    UPDATED_AT            TIMESTAMP(6)        DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_API_REQUEST_LOG PRIMARY KEY (API_REQUEST_LOG_ID),
    CONSTRAINT FK_API_LOG_USER  FOREIGN KEY (EMPLOYEE_NO) REFERENCES APP_USER (EMPLOYEE_NO),
    CONSTRAINT FK_API_LOG_POPUP FOREIGN KEY (POPUP_ID) REFERENCES POPUP_NOTICE (POPUP_ID),
    CONSTRAINT CK_API_LOG_ELAPSED CHECK (ELAPSED_MILLISECONDS IS NULL OR ELAPSED_MILLISECONDS >= 0),
    CONSTRAINT CK_API_LOG_STATUS  CHECK (HTTP_STATUS_CODE IS NULL OR HTTP_STATUS_CODE BETWEEN 100 AND 599),
    CONSTRAINT CK_API_LOG_SUCCESS CHECK (SUCCESS_YN IN ('Y', 'N'))
);
COMMENT ON TABLE API_REQUEST_LOG IS 'WPF API 요청 로그. 원본은 미사용 테이블이었으나 결과 API 수신 로그로 활용';

-- ---------------------------------------------------------------------
-- §9. 인덱스 (원본 동일)
-- ---------------------------------------------------------------------
CREATE INDEX IX_DEPARTMENT_PARENT      ON APP_DEPARTMENT (PARENT_DEPARTMENT_ID);
CREATE INDEX IX_USER_DEPARTMENT        ON APP_USER (DEPARTMENT_ID);
CREATE INDEX IX_USER_POSITION          ON APP_USER (POSITION_ID);
CREATE INDEX IX_POPUP_DISPLAY_PERIOD   ON POPUP_NOTICE (ACTIVE_YN, DISPLAY_START_AT, DISPLAY_END_AT);
CREATE INDEX IX_POPUP_TEMPLATE         ON POPUP_NOTICE (QUESTION_TEMPLATE_ID);
CREATE INDEX IX_TARGET_GROUP_POPUP     ON POPUP_TARGET_GROUP (POPUP_ID);
CREATE INDEX IX_TARGET_CONDITION_GROUP ON POPUP_TARGET_CONDITION (TARGET_GROUP_ID);
-- 원본 ix_question_template(QUESTION_TEMPLATE_ID, SORT_ORDER) / ix_option_question(QUESTION_ID, SORT_ORDER)은
-- UNIQUE 제약 UQ_QUESTION_SORT_ORDER / UQ_OPTION_SORT_ORDER가 같은 컬럼으로 이미 인덱스를 만들므로 생략한다.
-- (Oracle은 동일 컬럼 목록의 인덱스 중복을 ORA-01408로 거절한다. 21c XE 실행으로 확인.)
CREATE INDEX IX_STATUS_POPUP           ON USER_POPUP_STATUS (POPUP_ID);
CREATE INDEX IX_RESPONSE_POPUP_USER    ON POPUP_RESPONSE (POPUP_ID, EMPLOYEE_NO);
CREATE INDEX IX_ANSWER_RESPONSE        ON POPUP_RESPONSE_ANSWER (RESPONSE_ID);
CREATE INDEX IX_VALUE_ANSWER           ON POPUP_RESPONSE_VALUE (RESPONSE_ANSWER_ID);
CREATE INDEX IX_VIDEO_POPUP            ON VIDEO_VIEW_STATUS (POPUP_ID);
CREATE INDEX IX_API_LOG_RECEIVED_AT    ON API_REQUEST_LOG (REQUEST_RECEIVED_AT);

-- ---------------------------------------------------------------------
-- §10. (참고) Oracle에서는 UNIQUE 제약이 인덱스를 자동 생성하므로 추가 인덱스 불필요
-- ---------------------------------------------------------------------

-- ---------------------------------------------------------------------
-- §11. [신설] WPF 결과 수신 영수증 — 기준 3·4 (결과 API 멱등 처리)
-- ---------------------------------------------------------------------
-- 결과 항목(resultId)이 재전송되어도 한 번만 처리하기 위한 키 저장소.
-- POPUP_RESPONSE.CLIENT_REQUEST_ID는 제출(SUBMITTED)만 다루므로
-- CLOSED/HIDDEN/VIDEO_WATCHED를 포함한 모든 유형의 중복 방지에 별도 테이블을 둔다.
CREATE TABLE WPF_RESULT_RECEIPT
(
    RECEIPT_ID    NUMBER(19)         NOT NULL,
    RESULT_ID     VARCHAR2(64 CHAR)  NOT NULL,
    EMPLOYEE_NO   VARCHAR2(30 CHAR)  NOT NULL,
    POPUP_ID      VARCHAR2(50 CHAR)  NOT NULL,
    RESULT_TYPE   VARCHAR2(20 CHAR)  NOT NULL,
    RESULT_STATUS VARCHAR2(10 CHAR)  NOT NULL,
    RESULT_CODE   VARCHAR2(50 CHAR),
    RECEIVED_AT   TIMESTAMP(6)       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP) NOT NULL,
    CONSTRAINT PK_WPF_RESULT_RECEIPT PRIMARY KEY (RECEIPT_ID),
    CONSTRAINT UQ_WPF_RESULT_RECEIPT UNIQUE (RESULT_ID),
    CONSTRAINT CK_WPF_RESULT_TYPE   CHECK (RESULT_TYPE IN ('CLOSED', 'HIDDEN', 'SUBMITTED', 'VIDEO_WATCHED')),
    CONSTRAINT CK_WPF_RESULT_STATUS CHECK (RESULT_STATUS IN ('ACCEPTED', 'REJECTED'))
);
CREATE INDEX IX_WPF_RESULT_RECEIPT_USER ON WPF_RESULT_RECEIPT (EMPLOYEE_NO, RECEIVED_AT);
COMMENT ON TABLE  WPF_RESULT_RECEIPT IS 'WPF 결과 항목 멱등 키. 같은 RESULT_ID 재수신 시 DUPLICATE 응답';
COMMENT ON COLUMN WPF_RESULT_RECEIPT.RESULT_STATUS IS '최초 처리 결과. 재수신 응답은 DUPLICATE로 별도 표기';

COMMIT;
