-- =====================================================================
--  POPUP 스키마 — 개발용 샘플 데이터 (Oracle)
-- =====================================================================
--  용도 : 01_popup_schema_oracle.sql 적용 후 빈 스키마에서 WPF 조회·결과 API를 확인한다.
--  내용 : 부서 3 / 직급 2 / 사용자 3, 팝업 4종(TEXT·VIDEO·SURVEY·QUIZ), 대상 조건, 문항.
--  주의 : 운영 DB에 적용하지 않는다. 사번 E1001~E1003은 개발 SSO 모드(dev)에서 ssoToken으로 그대로 사용한다.
-- =====================================================================
-- 실행 계정의 스키마에 만든다. 별도 POPUP 계정이 있으면 popup 으로 접속해 실행하고(로컬 XE 21c),
-- 계정을 만들 수 없는 환경(원격 개발 DB 11g XE)에서는 앱 계정(zero-rule)으로 접속해 실행한 뒤
-- 서버 설정 custom.popup.schema 를 빈 값으로 둔다(스키마 분리 설정화, 2026-09-20). DBA가 대신 실행할 때만 아래를 켠다.
-- ALTER SESSION SET CURRENT_SCHEMA = POPUP;

-- 조직
INSERT INTO APP_DEPARTMENT (DEPARTMENT_ID, PARENT_DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_LEVEL, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('D000', NULL,   '본사',      1, 1, 'SAMPLE', 'SAMPLE');
INSERT INTO APP_DEPARTMENT (DEPARTMENT_ID, PARENT_DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_LEVEL, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('D100', 'D000', 'IT본부',    2, 1, 'SAMPLE', 'SAMPLE');
INSERT INTO APP_DEPARTMENT (DEPARTMENT_ID, PARENT_DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_LEVEL, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES ('D110', 'D100', '개발팀',    3, 1, 'SAMPLE', 'SAMPLE');

INSERT INTO APP_POSITION (POSITION_ID, POSITION_NAME, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES ('P01', '사원', 1, 'SAMPLE', 'SAMPLE');
INSERT INTO APP_POSITION (POSITION_ID, POSITION_NAME, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES ('P02', '팀장', 2, 'SAMPLE', 'SAMPLE');

INSERT INTO APP_USER (EMPLOYEE_NO, EMPLOYEE_NAME, DEPARTMENT_ID, POSITION_ID, HIRE_DATE, CREATED_BY, UPDATED_BY)
VALUES ('E1001', '김개발', 'D110', 'P01', DATE '2024-03-01', 'SAMPLE', 'SAMPLE');
INSERT INTO APP_USER (EMPLOYEE_NO, EMPLOYEE_NAME, DEPARTMENT_ID, POSITION_ID, HIRE_DATE, CREATED_BY, UPDATED_BY)
VALUES ('E1002', '이팀장', 'D110', 'P02', DATE '2018-07-15', 'SAMPLE', 'SAMPLE');
INSERT INTO APP_USER (EMPLOYEE_NO, EMPLOYEE_NAME, DEPARTMENT_ID, POSITION_ID, HIRE_DATE, CREATED_BY, UPDATED_BY)
VALUES ('E1003', '박본사', 'D000', 'P01', DATE '2026-01-02', 'SAMPLE', 'SAMPLE');

-- 문항 템플릿 (QUIZ 1개, SURVEY 1개)
INSERT INTO QUESTION_TEMPLATE (QUESTION_TEMPLATE_ID, TEMPLATE_GROUP_ID, TEMPLATE_NAME, TEMPLATE_TYPE, TEMPLATE_VERSION, CREATED_BY, UPDATED_BY)
VALUES (SEQ_QUESTION_TEMPLATE.NEXTVAL, 'TPL-QUIZ-SECURITY', '보안 교육 확인 퀴즈', 'QUIZ', 1, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_QUESTION (QUESTION_ID, QUESTION_TEMPLATE_ID, QUESTION_TYPE, QUESTION_TITLE, QUESTION_DESCRIPTION, REQUIRED_YN, SCORED_YN, QUESTION_SCORE, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_QUESTION.NEXTVAL, SEQ_QUESTION_TEMPLATE.CURRVAL, 'SINGLE_CHOICE', '보안 교육 내용을 확인했습니까?', '한 개를 선택하세요.', 'Y', 'Y', 10, 1, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_OPTION (OPTION_ID, QUESTION_ID, OPTION_VALUE, OPTION_TEXT, CORRECT_YN, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_OPTION.NEXTVAL, SEQ_POPUP_QUESTION.CURRVAL, 'YES', '예', 'Y', 1, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_OPTION (OPTION_ID, QUESTION_ID, OPTION_VALUE, OPTION_TEXT, CORRECT_YN, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_OPTION.NEXTVAL, SEQ_POPUP_QUESTION.CURRVAL, 'NO', '아니요', 'N', 2, 'SAMPLE', 'SAMPLE');

INSERT INTO QUESTION_TEMPLATE (QUESTION_TEMPLATE_ID, TEMPLATE_GROUP_ID, TEMPLATE_NAME, TEMPLATE_TYPE, TEMPLATE_VERSION, CREATED_BY, UPDATED_BY)
VALUES (SEQ_QUESTION_TEMPLATE.NEXTVAL, 'TPL-SURVEY-OFFICE', '사무환경 설문', 'SURVEY', 1, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_QUESTION (QUESTION_ID, QUESTION_TEMPLATE_ID, QUESTION_TYPE, QUESTION_TITLE, REQUIRED_YN, SCORED_YN, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_QUESTION.NEXTVAL, SEQ_QUESTION_TEMPLATE.CURRVAL, 'MULTIPLE_CHOICE', '개선이 필요한 항목을 모두 선택하세요.', 'Y', 'N', 1, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_OPTION (OPTION_ID, QUESTION_ID, OPTION_VALUE, OPTION_TEXT, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_OPTION.NEXTVAL, SEQ_POPUP_QUESTION.CURRVAL, 'CHAIR', '의자', 1, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_OPTION (OPTION_ID, QUESTION_ID, OPTION_VALUE, OPTION_TEXT, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_OPTION.NEXTVAL, SEQ_POPUP_QUESTION.CURRVAL, 'MONITOR', '모니터', 2, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_QUESTION (QUESTION_ID, QUESTION_TEMPLATE_ID, QUESTION_TYPE, QUESTION_TITLE, REQUIRED_YN, SCORED_YN, SORT_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_QUESTION.NEXTVAL, SEQ_QUESTION_TEMPLATE.CURRVAL, 'TEXT', '기타 의견', 'N', 'N', 2, 'SAMPLE', 'SAMPLE');

-- 팝업 4종 (노출 기간: 오늘 -1일 ~ +30일)
INSERT INTO POPUP_NOTICE (POPUP_ID, POPUP_TYPE, TITLE, DISPLAY_START_AT, DISPLAY_END_AT, DISPLAY_MODE, DISPLAY_ORDER, PERIOD_MODE, SIZE_MODE,
    POPUP_WIDTH, POPUP_HEIGHT, WIDTH_RATIO, HEIGHT_RATIO, MINIMUM_WIDTH, MINIMUM_HEIGHT, MAXIMUM_WIDTH, MAXIMUM_HEIGHT,
    SHOW_DO_NOT_SHOW_AGAIN_YN, HIDE_DAYS, CREATED_BY, UPDATED_BY)
VALUES ('SAMPLE-TEXT-001', 'TEXT', '9월 시스템 점검 안내', SYSTIMESTAMP - 1, SYSTIMESTAMP + 30, 'SEQUENTIAL', 10, 'FIXED', 'FIXED',
    560, 420, 0.7, 0.75, 480, 320, 1200, 900, 'Y', 7, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_CONTENT (POPUP_ID, CONTENT_TITLE, DESCRIPTION, CONTENT_BODY, CONTENT_OPTIONS, CREATED_BY, UPDATED_BY)
VALUES ('SAMPLE-TEXT-001', '서비스 점검 안내', '점검 시간 동안 접속이 제한됩니다.', '9월 21일(일) 02:00~06:00 점검 예정입니다.',
    '{"showContentHeader":true,"showPlainText":true,"highlightText":"작업 중인 내용을 저장해 주세요.","showHighlight":true,"bottomDescription":"자세히 보기","bottomDescriptionUrl":"https://intranet.example.com/notice/1","showBottomDescription":true,"markdownMode":false,"markdownContent":"","useBackgroundOverlay":true,"backgroundOverlayOpacity":0.45}',
    'SAMPLE', 'SAMPLE');

INSERT INTO POPUP_NOTICE (POPUP_ID, POPUP_TYPE, TITLE, DISPLAY_START_AT, DISPLAY_END_AT, DISPLAY_MODE, DISPLAY_ORDER, PERIOD_MODE, SIZE_MODE,
    POPUP_WIDTH, POPUP_HEIGHT, WIDTH_RATIO, HEIGHT_RATIO, MINIMUM_WIDTH, MINIMUM_HEIGHT, MAXIMUM_WIDTH, MAXIMUM_HEIGHT,
    COMPLETION_RATIO, ALLOW_CLOSE_BEFORE_COMPLETE_YN, CREATED_BY, UPDATED_BY)
VALUES ('SAMPLE-VIDEO-002', 'VIDEO', '정보보호 교육 영상', SYSTIMESTAMP - 1, SYSTIMESTAMP + 30, 'SEQUENTIAL', 20, 'FIXED', 'FIXED',
    960, 600, 0.8, 0.8, 640, 400, 1600, 1000, 0.9, 'N', 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_CONTENT (POPUP_ID, CONTENT_TITLE, DESCRIPTION, MEDIA_URL, CONTENT_OPTIONS, CREATED_BY, UPDATED_BY)
VALUES ('SAMPLE-VIDEO-002', '정보보호 교육', '영상을 끝까지 시청해 주세요.', 'http://localhost:8080/zero-rule-server/p/api/popups/video?path=sample.mp4',
    '{"showDescription":true,"showControls":true,"allowFullScreen":true,"allowPlaybackRateChange":false,"autoPlay":true,"isLoop":false,"defaultVolume":0.7,"useBackgroundOverlay":true,"backgroundOverlayOpacity":0.6}',
    'SAMPLE', 'SAMPLE');

INSERT INTO POPUP_NOTICE (POPUP_ID, QUESTION_TEMPLATE_ID, POPUP_TYPE, TITLE, DISPLAY_START_AT, DISPLAY_END_AT, DISPLAY_MODE, DISPLAY_ORDER, PERIOD_MODE, SIZE_MODE,
    POPUP_WIDTH, POPUP_HEIGHT, WIDTH_RATIO, HEIGHT_RATIO, MINIMUM_WIDTH, MINIMUM_HEIGHT, MAXIMUM_WIDTH, MAXIMUM_HEIGHT,
    PASSING_SCORE, CREATED_BY, UPDATED_BY)
VALUES ('SAMPLE-QUIZ-003', (SELECT QUESTION_TEMPLATE_ID FROM QUESTION_TEMPLATE WHERE TEMPLATE_GROUP_ID = 'TPL-QUIZ-SECURITY'),
    'QUIZ', '보안 교육 확인 퀴즈', SYSTIMESTAMP - 1, SYSTIMESTAMP + 30, 'SEQUENTIAL', 30, 'FIXED', 'FIXED',
    600, 480, 0.7, 0.75, 480, 320, 1200, 900, 10, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_CONTENT (POPUP_ID, CONTENT_TITLE, DESCRIPTION, CONTENT_OPTIONS, CREATED_BY, UPDATED_BY)
VALUES ('SAMPLE-QUIZ-003', '보안 교육 확인', '문항에 응답해 주세요.', '{"useBackgroundOverlay":true,"backgroundOverlayOpacity":0.45}', 'SAMPLE', 'SAMPLE');

INSERT INTO POPUP_NOTICE (POPUP_ID, QUESTION_TEMPLATE_ID, POPUP_TYPE, TITLE, DISPLAY_START_AT, DISPLAY_END_AT, DISPLAY_MODE, DISPLAY_ORDER, PERIOD_MODE, SIZE_MODE,
    POPUP_WIDTH, POPUP_HEIGHT, WIDTH_RATIO, HEIGHT_RATIO, MINIMUM_WIDTH, MINIMUM_HEIGHT, MAXIMUM_WIDTH, MAXIMUM_HEIGHT, CREATED_BY, UPDATED_BY)
VALUES ('SAMPLE-SURVEY-004', (SELECT QUESTION_TEMPLATE_ID FROM QUESTION_TEMPLATE WHERE TEMPLATE_GROUP_ID = 'TPL-SURVEY-OFFICE'),
    'SURVEY', '사무환경 설문', SYSTIMESTAMP - 1, SYSTIMESTAMP + 30, 'SEQUENTIAL', 40, 'FIXED', 'FIXED',
    600, 520, 0.7, 0.75, 480, 320, 1200, 900, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_CONTENT (POPUP_ID, CONTENT_TITLE, DESCRIPTION, CONTENT_OPTIONS, CREATED_BY, UPDATED_BY)
VALUES ('SAMPLE-SURVEY-004', '사무환경 설문', '의견을 남겨 주세요.', '{"useBackgroundOverlay":false,"backgroundOverlayOpacity":0.45}', 'SAMPLE', 'SAMPLE');

-- 대상 조건
--  TEXT   : 전사 (본사 D000 하위 포함)
--  VIDEO  : IT본부 하위 포함 (D100)
--  QUIZ   : 개발팀(D110) AND 사원(P01)  → E1001만
--  SURVEY : 입사일 >= 2020-01-01 OR 사번 E1002
INSERT INTO POPUP_TARGET_GROUP (TARGET_GROUP_ID, POPUP_ID, TARGET_NAME, TARGET_DESCRIPTION, GROUP_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_TARGET_GROUP.NEXTVAL, 'SAMPLE-TEXT-001', '전사', '본사 및 하위 부서', 1, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_TARGET_CONDITION (TARGET_CONDITION_ID, TARGET_GROUP_ID, CONDITION_TYPE, CONDITION_OPERATOR, DEPARTMENT_ID, INCLUDE_CHILD_YN, CONDITION_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_TARGET_CONDITION.NEXTVAL, SEQ_POPUP_TARGET_GROUP.CURRVAL, 'DEPARTMENT', '=', 'D000', 'Y', 1, 'SAMPLE', 'SAMPLE');

INSERT INTO POPUP_TARGET_GROUP (TARGET_GROUP_ID, POPUP_ID, TARGET_NAME, TARGET_DESCRIPTION, GROUP_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_TARGET_GROUP.NEXTVAL, 'SAMPLE-VIDEO-002', 'IT본부', 'IT본부 및 하위', 1, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_TARGET_CONDITION (TARGET_CONDITION_ID, TARGET_GROUP_ID, CONDITION_TYPE, CONDITION_OPERATOR, DEPARTMENT_ID, INCLUDE_CHILD_YN, CONDITION_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_TARGET_CONDITION.NEXTVAL, SEQ_POPUP_TARGET_GROUP.CURRVAL, 'DEPARTMENT', '=', 'D100', 'Y', 1, 'SAMPLE', 'SAMPLE');

INSERT INTO POPUP_TARGET_GROUP (TARGET_GROUP_ID, POPUP_ID, TARGET_NAME, TARGET_DESCRIPTION, GROUP_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_TARGET_GROUP.NEXTVAL, 'SAMPLE-QUIZ-003', '개발팀 사원', '개발팀 AND 사원', 1, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_TARGET_CONDITION (TARGET_CONDITION_ID, TARGET_GROUP_ID, CONDITION_TYPE, CONDITION_OPERATOR, DEPARTMENT_ID, INCLUDE_CHILD_YN, CONDITION_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_TARGET_CONDITION.NEXTVAL, SEQ_POPUP_TARGET_GROUP.CURRVAL, 'DEPARTMENT', '=', 'D110', 'N', 1, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_TARGET_CONDITION (TARGET_CONDITION_ID, TARGET_GROUP_ID, CONDITION_TYPE, CONDITION_OPERATOR, POSITION_ID, CONDITION_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_TARGET_CONDITION.NEXTVAL, SEQ_POPUP_TARGET_GROUP.CURRVAL, 'POSITION', '=', 'P01', 2, 'SAMPLE', 'SAMPLE');

INSERT INTO POPUP_TARGET_GROUP (TARGET_GROUP_ID, POPUP_ID, TARGET_NAME, TARGET_DESCRIPTION, GROUP_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_TARGET_GROUP.NEXTVAL, 'SAMPLE-SURVEY-004', '2020년 이후 입사', '입사일 기준', 1, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_TARGET_CONDITION (TARGET_CONDITION_ID, TARGET_GROUP_ID, CONDITION_TYPE, CONDITION_OPERATOR, CONDITION_DATE_VALUE, CONDITION_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_TARGET_CONDITION.NEXTVAL, SEQ_POPUP_TARGET_GROUP.CURRVAL, 'HIRE_DATE', '>=', DATE '2020-01-01', 1, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_TARGET_GROUP (TARGET_GROUP_ID, POPUP_ID, TARGET_NAME, TARGET_DESCRIPTION, GROUP_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_TARGET_GROUP.NEXTVAL, 'SAMPLE-SURVEY-004', '팀장 개별 지정', '사번 지정', 2, 'SAMPLE', 'SAMPLE');
INSERT INTO POPUP_TARGET_CONDITION (TARGET_CONDITION_ID, TARGET_GROUP_ID, CONDITION_TYPE, CONDITION_OPERATOR, EMPLOYEE_NO, CONDITION_ORDER, CREATED_BY, UPDATED_BY)
VALUES (SEQ_POPUP_TARGET_CONDITION.NEXTVAL, SEQ_POPUP_TARGET_GROUP.CURRVAL, 'EMPLOYEE', '=', 'E1002', 1, 'SAMPLE', 'SAMPLE');

COMMIT;

-- 기대 결과 (GET /p/api/wpf/popups)
--  E1001 (개발팀·사원·2024 입사): TEXT, VIDEO, QUIZ, SURVEY
--  E1002 (개발팀·팀장·2018 입사): TEXT, VIDEO, SURVEY(사번 지정)
--  E1003 (본사·사원·2026 입사)  : TEXT, SURVEY
