-- 기존 DB용: POPUP 소유 계정에서 서버 배포 전에 한 번 실행한다.
-- 신규 DB는 01_popup_schema_oracle.sql에 이미 포함되어 있으므로 실행하지 않는다.
ALTER TABLE POPUP_QUESTION ADD (
    OPTION_LAYOUT VARCHAR2(10 CHAR) DEFAULT 'VERTICAL' NOT NULL
);
ALTER TABLE POPUP_QUESTION ADD CONSTRAINT CK_QUESTION_OPTION_LAYOUT
    CHECK (OPTION_LAYOUT IN ('VERTICAL', 'HORIZONTAL'));
COMMENT ON COLUMN POPUP_QUESTION.OPTION_LAYOUT IS '문항별 선택지 배치: VERTICAL / HORIZONTAL';
