-- =====================================================================================================
-- 08_legacy_data_constraints_oracle.sql — 과거 데이터 보정 후 제약 추가 (2026-09-28, 설계 18 L-4 / D-3·D-4·C-23)
-- -----------------------------------------------------------------------------------------------------
-- 배경: 서버·WPF·관리자 웹에 과거·이관 데이터용 기본값 분기가 남아 있었다. L-4 코드는 이 분기를 지우므로
--       기존 DB는 **L-4 서버·WPF 배포 전에** 이 스크립트로 데이터를 맞추고 제약을 걸어야 한다.
--   1) POPUP_NOTICE.DISPLAY_MODE  : SEQUENTIAL / SIMULTANEOUS 외 값 → SEQUENTIAL, CHECK 추가
--                                   (서버 매퍼의 CASE fallback 제거 — S-14)
--   2) POPUP_NOTICE 크기 컬럼 8개 : NULL → 기존 서버 기본값(900/620/0.7/0.75/480/320/1200/900), NOT NULL
--                                   (서버 toResponseDto 기본값 제거 — S-15)
--   3) POPUP_QUESTION RATING5     : SINGLE_CHOICE + OPTION_LAYOUT HORIZONTAL로 이관, 선택지가 없으면 1~5 생성,
--                                   QUESTION_TYPE CHECK 추가 (WPF RATING5 매핑 제거 — S-17·C-25)
--   4) TEXT CONTENT_OPTIONS       : showHighlight / showBottomDescription 키가 없으면 기존 fallback 규칙으로 채움
--                                   (문구가 있으면 true) (WPF·관리자 웹의 null fallback 제거 — C-23)
-- 실행: 팝업 테이블이 있는 계정으로 SQL*Plus 실행 (NLS_LANG=KOREAN_KOREA.AL32UTF8).
--       - 로컬 XE(POPUP 계정 스키마)      : @08_legacy_data_constraints_oracle.sql POPUP.
--       - 원격 개발 DB(앱 계정 zero-rule) : @08_legacy_data_constraints_oracle.sql ""
--       전제: 05_question_option_layout_oracle.sql(OPTION_LAYOUT 컬럼) 적용 완료.
-- 여러 번 실행해도 결과가 같다(이미 있는 제약·NOT NULL은 건너뜀).
-- =====================================================================================================
SET PAGESIZE 200 LINESIZE 250 LONG 4000 TRIMSPOOL ON FEEDBACK ON DEFINE ON SERVEROUTPUT ON
DEFINE S = &1
COLUMN POPUP_ID FORMAT A24
COLUMN DISPLAY_MODE FORMAT A20
COLUMN QUESTION_TITLE FORMAT A40

PROMPT === 1. 확인: DISPLAY_MODE 비정상 행 ===
SELECT POPUP_ID, DISPLAY_MODE FROM &S.POPUP_NOTICE
 WHERE DISPLAY_MODE NOT IN ('SEQUENTIAL', 'SIMULTANEOUS');

PROMPT === 2. 확인: 크기 컬럼 NULL 행 ===
SELECT POPUP_ID FROM &S.POPUP_NOTICE
 WHERE POPUP_WIDTH IS NULL OR POPUP_HEIGHT IS NULL OR WIDTH_RATIO IS NULL OR HEIGHT_RATIO IS NULL
    OR MINIMUM_WIDTH IS NULL OR MINIMUM_HEIGHT IS NULL OR MAXIMUM_WIDTH IS NULL OR MAXIMUM_HEIGHT IS NULL;

PROMPT === 3. 확인: RATING5 문항 (QUIZ 소속이면 정답 선택지를 관리자 화면에서 지정해야 재저장 가능) ===
SELECT q.QUESTION_ID, q.QUESTION_TEMPLATE_ID, q.QUESTION_TITLE,
       (SELECT COUNT(*) FROM &S.POPUP_OPTION o WHERE o.QUESTION_ID = q.QUESTION_ID) OPTION_CNT,
       (SELECT LISTAGG(n.POPUP_ID || ':' || n.POPUP_TYPE, ',') WITHIN GROUP (ORDER BY n.POPUP_ID)
          FROM &S.POPUP_NOTICE n WHERE n.QUESTION_TEMPLATE_ID = q.QUESTION_TEMPLATE_ID) POPUPS
  FROM &S.POPUP_QUESTION q WHERE q.QUESTION_TYPE NOT IN ('SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'TEXT');

PROMPT === 4. 확인: 표시 플래그가 없는 TEXT 팝업 ===
SELECT c.POPUP_ID,
       CASE WHEN DBMS_LOB.INSTR(c.CONTENT_OPTIONS, '"showHighlight":') > 0 THEN 'Y' ELSE 'N' END HAS_SHOW_HIGHLIGHT,
       CASE WHEN DBMS_LOB.INSTR(c.CONTENT_OPTIONS, '"showBottomDescription":') > 0 THEN 'Y' ELSE 'N' END HAS_SHOW_BOTTOM
  FROM &S.POPUP_CONTENT c JOIN &S.POPUP_NOTICE n ON n.POPUP_ID = c.POPUP_ID
 WHERE n.POPUP_TYPE = 'TEXT'
   AND (c.CONTENT_OPTIONS IS NULL
        OR DBMS_LOB.INSTR(c.CONTENT_OPTIONS, '"showHighlight":') = 0
        OR DBMS_LOB.INSTR(c.CONTENT_OPTIONS, '"showBottomDescription":') = 0);

PROMPT === 5. 보정: DISPLAY_MODE ===
UPDATE &S.POPUP_NOTICE
   SET DISPLAY_MODE = 'SEQUENTIAL', UPDATED_BY = 'CLEANUP',
       UPDATED_AT = CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP)
 WHERE DISPLAY_MODE NOT IN ('SEQUENTIAL', 'SIMULTANEOUS');

PROMPT === 6. 보정: 크기 컬럼 NULL → 기존 서버 기본값 ===
UPDATE &S.POPUP_NOTICE
   SET POPUP_WIDTH    = NVL(POPUP_WIDTH, 900),
       POPUP_HEIGHT   = NVL(POPUP_HEIGHT, 620),
       WIDTH_RATIO    = NVL(WIDTH_RATIO, 0.7),
       HEIGHT_RATIO   = NVL(HEIGHT_RATIO, 0.75),
       MINIMUM_WIDTH  = NVL(MINIMUM_WIDTH, 480),
       MINIMUM_HEIGHT = NVL(MINIMUM_HEIGHT, 320),
       MAXIMUM_WIDTH  = NVL(MAXIMUM_WIDTH, 1200),
       MAXIMUM_HEIGHT = NVL(MAXIMUM_HEIGHT, 900),
       UPDATED_BY = 'CLEANUP', UPDATED_AT = CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP)
 WHERE POPUP_WIDTH IS NULL OR POPUP_HEIGHT IS NULL OR WIDTH_RATIO IS NULL OR HEIGHT_RATIO IS NULL
    OR MINIMUM_WIDTH IS NULL OR MINIMUM_HEIGHT IS NULL OR MAXIMUM_WIDTH IS NULL OR MAXIMUM_HEIGHT IS NULL;

PROMPT === 7. 보정: RATING5 → 선택지 1~5 생성(선택지가 없을 때만) 후 SINGLE_CHOICE + HORIZONTAL ===
INSERT INTO &S.POPUP_OPTION (OPTION_ID, QUESTION_ID, OPTION_VALUE, OPTION_TEXT, CORRECT_YN, SORT_ORDER, CREATED_BY, UPDATED_BY)
SELECT &S.SEQ_POPUP_OPTION.NEXTVAL, x.QUESTION_ID, x.N, x.N, 'N', x.N, 'CLEANUP', 'CLEANUP'
  FROM (SELECT q.QUESTION_ID, TO_CHAR(r.N) N
          FROM &S.POPUP_QUESTION q
         CROSS JOIN (SELECT LEVEL N FROM DUAL CONNECT BY LEVEL <= 5) r
         WHERE q.QUESTION_TYPE = 'RATING5'
           AND NOT EXISTS (SELECT 1 FROM &S.POPUP_OPTION o WHERE o.QUESTION_ID = q.QUESTION_ID)) x;
UPDATE &S.POPUP_QUESTION
   SET QUESTION_TYPE = 'SINGLE_CHOICE', OPTION_LAYOUT = 'HORIZONTAL', UPDATED_BY = 'CLEANUP',
       UPDATED_AT = CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP)
 WHERE QUESTION_TYPE = 'RATING5';

PROMPT === 8. 보정: TEXT showHighlight / showBottomDescription 채우기 ===
UPDATE &S.POPUP_CONTENT c
   SET CONTENT_OPTIONS =
         CASE WHEN c.CONTENT_OPTIONS IS NULL OR REGEXP_LIKE(c.CONTENT_OPTIONS, '^\s*\{\s*\}\s*$')
              THEN TO_CLOB('{"showHighlight":'
                   || CASE WHEN REGEXP_LIKE(c.CONTENT_OPTIONS, '"highlightText":"\s*[^"[:space:]]') THEN 'true' ELSE 'false' END || '}')
              ELSE REGEXP_REPLACE(c.CONTENT_OPTIONS, '^\s*\{', '{"showHighlight":'
                   || CASE WHEN REGEXP_LIKE(c.CONTENT_OPTIONS, '"highlightText":"\s*[^"[:space:]]') THEN 'true' ELSE 'false' END || ',', 1, 1)
         END,
       UPDATED_BY = 'CLEANUP', UPDATED_AT = CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP)
 WHERE c.POPUP_ID IN (SELECT POPUP_ID FROM &S.POPUP_NOTICE WHERE POPUP_TYPE = 'TEXT')
   AND (c.CONTENT_OPTIONS IS NULL OR DBMS_LOB.INSTR(c.CONTENT_OPTIONS, '"showHighlight":') = 0);
UPDATE &S.POPUP_CONTENT c
   SET CONTENT_OPTIONS =
         REGEXP_REPLACE(c.CONTENT_OPTIONS, '^\s*\{', '{"showBottomDescription":'
             || CASE WHEN REGEXP_LIKE(c.CONTENT_OPTIONS, '"bottomDescription(Url)?":"\s*[^"[:space:]]') THEN 'true' ELSE 'false' END || ',', 1, 1),
       UPDATED_BY = 'CLEANUP', UPDATED_AT = CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' AS TIMESTAMP)
 WHERE c.POPUP_ID IN (SELECT POPUP_ID FROM &S.POPUP_NOTICE WHERE POPUP_TYPE = 'TEXT')
   AND DBMS_LOB.INSTR(c.CONTENT_OPTIONS, '"showBottomDescription":') = 0;
COMMIT;

PROMPT === 9. 제약: DISPLAY_MODE CHECK · 크기 NOT NULL · QUESTION_TYPE CHECK (이미 있으면 건너뜀) ===
DECLARE
    PROCEDURE run(p_sql VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE p_sql;
        DBMS_OUTPUT.PUT_LINE('OK   ' || p_sql);
    EXCEPTION
        WHEN OTHERS THEN
            -- ORA-02264 제약 이름 중복, ORA-02275 동일 제약 존재, ORA-01442 이미 NOT NULL
            IF SQLCODE IN (-2264, -2275, -1442) THEN
                DBMS_OUTPUT.PUT_LINE('SKIP ' || p_sql);
            ELSE
                RAISE;
            END IF;
    END;
BEGIN
    run('ALTER TABLE &S.POPUP_NOTICE ADD CONSTRAINT CK_POPUP_DISPLAY_MODE CHECK (DISPLAY_MODE IN (''SEQUENTIAL'', ''SIMULTANEOUS''))');
    run('ALTER TABLE &S.POPUP_NOTICE MODIFY (POPUP_WIDTH NOT NULL)');
    run('ALTER TABLE &S.POPUP_NOTICE MODIFY (POPUP_HEIGHT NOT NULL)');
    run('ALTER TABLE &S.POPUP_NOTICE MODIFY (WIDTH_RATIO NOT NULL)');
    run('ALTER TABLE &S.POPUP_NOTICE MODIFY (HEIGHT_RATIO NOT NULL)');
    run('ALTER TABLE &S.POPUP_NOTICE MODIFY (MINIMUM_WIDTH NOT NULL)');
    run('ALTER TABLE &S.POPUP_NOTICE MODIFY (MINIMUM_HEIGHT NOT NULL)');
    run('ALTER TABLE &S.POPUP_NOTICE MODIFY (MAXIMUM_WIDTH NOT NULL)');
    run('ALTER TABLE &S.POPUP_NOTICE MODIFY (MAXIMUM_HEIGHT NOT NULL)');
    run('ALTER TABLE &S.POPUP_QUESTION ADD CONSTRAINT CK_QUESTION_TYPE CHECK (QUESTION_TYPE IN (''SINGLE_CHOICE'', ''MULTIPLE_CHOICE'', ''TEXT''))');
END;
/
COMMENT ON TABLE  &S.POPUP_QUESTION IS '문항. QUESTION_TYPE: SINGLE_CHOICE / MULTIPLE_CHOICE / TEXT';
COMMENT ON COLUMN &S.POPUP_NOTICE.PASSING_SCORE IS 'QUIZ 통과 점수. QUIZ 팝업은 WPF 응답 최상위 passingScore로 내려줌(설계 12)';

PROMPT === 10. 결과 확인 (모두 0 이어야 함) ===
SELECT (SELECT COUNT(*) FROM &S.POPUP_NOTICE WHERE DISPLAY_MODE NOT IN ('SEQUENTIAL', 'SIMULTANEOUS')) BAD_DISPLAY_MODE,
       (SELECT COUNT(*) FROM &S.POPUP_QUESTION WHERE QUESTION_TYPE NOT IN ('SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'TEXT')) BAD_QUESTION_TYPE,
       (SELECT COUNT(*) FROM &S.POPUP_CONTENT c JOIN &S.POPUP_NOTICE n ON n.POPUP_ID = c.POPUP_ID
         WHERE n.POPUP_TYPE = 'TEXT' AND (c.CONTENT_OPTIONS IS NULL
               OR DBMS_LOB.INSTR(c.CONTENT_OPTIONS, '"showHighlight":') = 0
               OR DBMS_LOB.INSTR(c.CONTENT_OPTIONS, '"showBottomDescription":') = 0)) TEXT_MISSING_FLAGS
  FROM DUAL;
EXIT
